set(_CATKIN_CURRENT_PACKAGE "ar3_moveit_config")
set(ar3_moveit_config_VERSION "0.3.0")
set(ar3_moveit_config_MAINTAINER "ar3_moveit_2 <yelidyc@gmail.com>")
set(ar3_moveit_config_PACKAGE_FORMAT "1")
set(ar3_moveit_config_BUILD_DEPENDS )
set(ar3_moveit_config_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "ar3_description")
set(ar3_moveit_config_BUILDTOOL_DEPENDS "catkin")
set(ar3_moveit_config_BUILDTOOL_EXPORT_DEPENDS )
set(ar3_moveit_config_EXEC_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "ar3_description")
set(ar3_moveit_config_RUN_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "ar3_description")
set(ar3_moveit_config_TEST_DEPENDS )
set(ar3_moveit_config_DOC_DEPENDS )
set(ar3_moveit_config_URL_WEBSITE "http://moveit.ros.org/")
set(ar3_moveit_config_URL_BUGTRACKER "https://github.com/ros-planning/moveit/issues")
set(ar3_moveit_config_URL_REPOSITORY "https://github.com/ros-planning/moveit")
set(ar3_moveit_config_DEPRECATED "")