# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
import cv2

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 620)
        Form.setStyleSheet("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(520, 190, 161, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 140, 161, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(520, 90, 161, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(420, 290, 21, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(420, 330, 21, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(420, 370, 21, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(420, 410, 21, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(420, 450, 21, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(420, 490, 21, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(420, 530, 21, 20))
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 90, 101, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(470, 570, 141, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(410, 190, 101, 41))
        self.pushButton_6.setStyleSheet("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(410, 140, 101, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(610, 290, 61, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(610, 330, 61, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(610, 370, 61, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(610, 530, 61, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(610, 490, 61, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(610, 410, 61, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(610, 450, 61, 25))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(440, 290, 160, 16))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(Form)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(440, 330, 160, 16))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(Form)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(440, 370, 160, 16))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_4 = QtWidgets.QSlider(Form)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(440, 410, 160, 16))
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalSlider_5 = QtWidgets.QSlider(Form)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(440, 450, 160, 16))
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.horizontalSlider_6 = QtWidgets.QSlider(Form)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(440, 530, 160, 16))
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.horizontalSlider_7 = QtWidgets.QSlider(Form)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(440, 490, 160, 16))
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(200, 10, 341, 51))
        self.label_8.setStyleSheet("\n"
"font: 75 11pt \"Sans\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(440, 260, 221, 17))
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(50, 90, 311, 261))
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Form)
        self.pushButton_6.clicked.connect(self.foto)
        self.pushButton_7.clicked.connect(self.video)
        self.pushButton_3.clicked.connect(self.posicioninicio)
        self.pushButton.clicked.connect(self.modomanual)
        self.pushButton_2.clicked.connect(self.modoautomatico)
        self.pushButton_4.clicked.connect(self.xbox)
        self.pushButton_5.clicked.connect(self.planear)
        self.lineEdit.textEdited['QString'].connect(self.valorJ1)
        self.lineEdit_2.textEdited['QString'].connect(self.valorJ2)
        self.lineEdit_3.textEdited['QString'].connect(self.valorJ3)
        self.lineEdit_8.textEdited['QString'].connect(self.J4)
        self.lineEdit_9.textEdited['QString'].connect(self.J5)
        self.lineEdit_7.textEdited['QString'].connect(self.J6)
        self.lineEdit_6.textEdited['QString'].connect(self.valorJ7)
        self.horizontalSlider.sliderMoved['int'].connect(self.J1)
        self.horizontalSlider_2.sliderMoved['int'].connect(self.J2)
        self.horizontalSlider_3.sliderMoved['int'].connect(self.J3)
        self.horizontalSlider_4.sliderMoved['int'].connect(self.J4)
        self.horizontalSlider_5.sliderMoved['int'].connect(self.J5)
        self.horizontalSlider_7.sliderMoved['int'].connect(self.J6)
        self.horizontalSlider_6.sliderMoved['int'].connect(self.J7)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Modo Manual"))
        self.pushButton_2.setText(_translate("Form", "Modo Automatico"))
        self.pushButton_3.setText(_translate("Form", "Posicion de inicio"))
        self.label.setText(_translate("Form", "J1"))
        self.label_2.setText(_translate("Form", "J2"))
        self.label_3.setText(_translate("Form", "J3"))
        self.label_4.setText(_translate("Form", "J4"))
        self.label_5.setText(_translate("Form", "J5"))
        self.label_6.setText(_translate("Form", "J6"))
        self.label_7.setText(_translate("Form", "J7"))
        self.pushButton_4.setText(_translate("Form", "XBOX"))
        self.pushButton_5.setText(_translate("Form", "PLANEAR"))
        self.pushButton_6.setText(_translate("Form", "Foto"))
        self.pushButton_7.setText(_translate("Form", "VIdeo"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:20pt;\">FILMMAKER ROBOT ARM</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "Control de posicion de motores"))

    #def foto(self):
     #   print ("Foto")

   # def video(self):
     #   print ("Video")

    def posicioninicio(self):
        print ("Video")
    
    def modomanual(self):
        print ("Modo manual_GUI")
    
    def xbox(self):
        print ("MODO_MANUAL_XBOX")
    
    def modoautomatico(self):
        self.xbox_status=2
        print ("Modo automatico")

    def planear(self):
        print ("PLANEAR") 

    def valorJ1(self):
        print ("J1")       

    def valorJ2(self):
        print ("J2")       

    def valorJ3(self):
        print ("J3")  

    def valorJ4(self):
        print ("J4")  

    def valorJ5(self):
        print ("J5")  

    def valorJ6(self):
        print ("J6")  

    def valorJ7(self):
        print ("J7")  
    
    def J1(self):
        print ("slider")

    def J2(self):
        print ("slider")

    def J3(self):
        print ("slider")

    def J4(self):
        print ("slider")

    def J5(self):
        print ("slider")

    def J6(self):
        print ("slider")

    def J7(self):
        print ("slider")
    #    float (self.M7)
    #    self.M7= (self.horizontalSlider_7.value())
    #    self.lineEdit_6.setText(str(self.M7))
    
    def foto(self):
        self.Work = Work()
        self.Work.start()
        self.Work.Imageupd.connect(self.Imageupd_slot)

    def Imageupd_slot(self, Image):
        self.label_10.setPixmap(QPixmap.fromImage(Image))

    def video(self):
        self.label_10.clear()
        self.Work.stop()

class Work(QThread):
    Imageupd = pyqtSignal(QImage)
    def run(self):
        self.hilo_corriendo = True
        cap = cv2.VideoCapture(0)
        while self.hilo_corriendo:
            ret, frame = cap.read()
            if ret:
                Image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                flip = cv2.flip(Image, 1)
                convertir_QT = QImage(flip.data, flip.shape[1], flip.shape[0], QImage.Format_RGB888)
                pic = convertir_QT.scaled(640, 240, Qt.KeepAspectRatio)
                self.Imageupd.emit(pic)
    def stop(self):
        self.hilo_corriendo = False
        self.quit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
