# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#-------------------------ROS IMPORTS----------------------------------
import sys
import copy
import rospy
import moveit_commander
import moveit_msgs.msg
import geometry_msgs.msg
from math import pi
from std_msgs.msg import String, Float32
from moveit_commander.conversions import pose_to_list
from geometry_msgs.msg import Twist
from sensor_msgs.msg import Joy
#-------------------QT IMPORTS----------------------------------
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
import cv2
from T1 import Ui_trayectoria1
from T2 import Ui_trayectoria2
from T3 import Ui_trayectoria3
from T4 import Ui_trayectoria4
from T5 import Ui_trayectoria5
from T6 import Ui_trayectoria6
global img_counter
img_counter=0
#-------------------------qt CONFIG----------------------------------
class Ui_GUI_FMA(object): 
    def T1(self):
        self.window=QtWidgets.QWidget()
        self.ui= Ui_trayectoria1()
        self.ui.setupUi(self.window)
        self.window.show()
    def T2(self):
        self.window=QtWidgets.QWidget()
        self.ui= Ui_trayectoria2()
        self.ui.setupUi(self.window)
        self.window.show()
    def T3(self):
        self.window=QtWidgets.QWidget()
        self.ui= Ui_trayectoria3()
        self.ui.setupUi(self.window)
        self.window.show()
    def T4(self):
        self.window=QtWidgets.QWidget()
        self.ui= Ui_trayectoria4()
        self.ui.setupUi(self.window)
        self.window.show()
    def T5(self):
        self.window=QtWidgets.QWidget()
        self.ui= Ui_trayectoria5()
        self.ui.setupUi(self.window)
        self.window.show()
    def T6(self):
        self.window=QtWidgets.QWidget()
        self.ui= Ui_trayectoria6()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def setupUi(self, GUI_FMA):

        self.robot = moveit_commander.RobotCommander()
        self.scene = moveit_commander.PlanningSceneInterface()
        self.group_name = "manipulator"
        self.move_group = moveit_commander.MoveGroupCommander(self.group_name)

        self.planning_frame = self.move_group.get_planning_frame()
        print("============ Planning frame: %s" % self.planning_frame)

        # We can also print the name of the end-effector link for this group:
        self.eef_link = self.move_group.get_end_effector_link()
        print("============ End effector link: %s" % self.eef_link)

        # We can get a list of all the groups in the robot:
        self.group_names = self.robot.get_group_names()
        print("============ Available Planning Groups:", self.robot.get_group_names())

        # Sometimes for debugging it is useful to print the entire state of the
        # robot:
        print("============ Printing robot state")
        print(self.robot.get_current_state())
        print("")
        
        rospy.Subscriber("joy", Joy, self.control) 
        #rospy.Subscriber('position_state_x', Float32, callback)
        #rospy.Subscriber('position_state_y', Float32, callback1)

        #---------------------MOTORES---------------------------------
        self.M1=0.0
        self.M2=0.0
        self.M3=0.0
        self.M4=0.0
        self.M5=0.0
        self.M6=0.0
        #--------------------BOTONES---------------------------------
        self.xbox_status=0
        self.counter=0
        self.A=0.0   
        self.B=0.0  
        self.X=0.0
        self.Y=0.0
        self.RB=0.0
        self.LB=0.0
        self.DI=0.0  #Boton derecha/izquierda
        self.UD=0.0  #Boton UP/DOWN
        self.SQ=0.0 
        self.img_counter=0
        #---------------------------------------------------------------

        GUI_FMA.setObjectName("GUI_FMA")
        GUI_FMA.resize(700, 620)
        GUI_FMA.setStyleSheet("")
        self.pushButton = QtWidgets.QPushButton(GUI_FMA)
        self.pushButton.setGeometry(QtCore.QRect(520, 190, 161, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(GUI_FMA)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 140, 161, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(GUI_FMA)
        self.pushButton_3.setGeometry(QtCore.QRect(520, 90, 161, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(GUI_FMA)
        self.label.setGeometry(QtCore.QRect(420, 290, 21, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(GUI_FMA)
        self.label_2.setGeometry(QtCore.QRect(420, 330, 21, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(GUI_FMA)
        self.label_3.setGeometry(QtCore.QRect(420, 370, 21, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(GUI_FMA)
        self.label_4.setGeometry(QtCore.QRect(420, 410, 21, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(GUI_FMA)
        self.label_5.setGeometry(QtCore.QRect(420, 450, 21, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(GUI_FMA)
        self.label_6.setGeometry(QtCore.QRect(420, 490, 21, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(GUI_FMA)
        self.label_7.setGeometry(QtCore.QRect(420, 530, 21, 20))
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(GUI_FMA)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 90, 101, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(GUI_FMA)
        self.pushButton_5.setGeometry(QtCore.QRect(470, 570, 141, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(GUI_FMA)
        self.pushButton_6.setGeometry(QtCore.QRect(410, 190, 101, 41))
        self.pushButton_6.setStyleSheet("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(GUI_FMA)
        self.pushButton_7.setGeometry(QtCore.QRect(410, 140, 101, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit = QtWidgets.QLineEdit(GUI_FMA)
        self.lineEdit.setGeometry(QtCore.QRect(610, 290, 61, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(GUI_FMA)
        self.lineEdit_2.setGeometry(QtCore.QRect(610, 330, 61, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(GUI_FMA)
        self.lineEdit_3.setGeometry(QtCore.QRect(610, 370, 61, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(GUI_FMA)
        self.lineEdit_6.setGeometry(QtCore.QRect(610, 530, 61, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(GUI_FMA)
        self.lineEdit_7.setGeometry(QtCore.QRect(610, 490, 61, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(GUI_FMA)
        self.lineEdit_8.setGeometry(QtCore.QRect(610, 410, 61, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(GUI_FMA)
        self.lineEdit_9.setGeometry(QtCore.QRect(610, 450, 61, 25))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalSlider = QtWidgets.QSlider(GUI_FMA)
        self.horizontalSlider.setGeometry(QtCore.QRect(440, 290, 160, 16))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setMinimum(-170)
        self.horizontalSlider.setMaximum(170)
        self.horizontalSlider_2 = QtWidgets.QSlider(GUI_FMA)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(440, 330, 160, 16))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_2.setMinimum(-40)
        self.horizontalSlider_2.setMaximum(90)
        self.horizontalSlider_3 = QtWidgets.QSlider(GUI_FMA)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(440, 370, 160, 16))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_3.setMinimum(0)
        self.horizontalSlider_3.setMaximum(144)
        self.horizontalSlider_4 = QtWidgets.QSlider(GUI_FMA)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(440, 410, 160, 16))
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalSlider_4.setMinimum(-165)
        self.horizontalSlider_4.setMaximum(165)
        self.horizontalSlider_5 = QtWidgets.QSlider(GUI_FMA)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(440, 450, 160, 16))
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.horizontalSlider_6 = QtWidgets.QSlider(GUI_FMA)
        self.horizontalSlider_5.setMinimum(-104)
        self.horizontalSlider_5.setMaximum(104)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(440, 530, 160, 16))
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.horizontalSlider_6.setMinimum(-148)
        self.horizontalSlider_6.setMaximum(148)
        self.horizontalSlider_7 = QtWidgets.QSlider(GUI_FMA)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(440, 490, 160, 16))
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.horizontalSlider_7.setMinimum(-170)
        self.horizontalSlider_7.setMaximum(170)
        self.label_8 = QtWidgets.QLabel(GUI_FMA)
        self.label_8.setGeometry(QtCore.QRect(200, 10, 341, 51))
        self.label_8.setStyleSheet("\n"
"font: 75 11pt \"Sans\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(GUI_FMA)
        self.label_9.setGeometry(QtCore.QRect(440, 260, 221, 17))
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(GUI_FMA)
        self.label_10.setGeometry(QtCore.QRect(40, 90, 311, 261))
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.pushButton_8 = QtWidgets.QPushButton(GUI_FMA)
        self.pushButton_8.setGeometry(QtCore.QRect(80, 450, 101, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(GUI_FMA)
        self.pushButton_9.setGeometry(QtCore.QRect(190, 450, 101, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(GUI_FMA)
        self.pushButton_10.setGeometry(QtCore.QRect(190, 490, 101, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(GUI_FMA)
        self.pushButton_11.setGeometry(QtCore.QRect(80, 490, 101, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(GUI_FMA)
        self.pushButton_12.setGeometry(QtCore.QRect(80, 530, 101, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(GUI_FMA)
        self.pushButton_13.setGeometry(QtCore.QRect(190, 530, 101, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(GUI_FMA)
        self.pushButton_14.setGeometry(QtCore.QRect(160, 360, 41, 31))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_16 = QtWidgets.QPushButton(GUI_FMA)
        self.pushButton_16.setGeometry(QtCore.QRect(210, 360, 41, 31))
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_11 = QtWidgets.QLabel(GUI_FMA)
        self.label_11.setGeometry(QtCore.QRect(40, 370, 121, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(GUI_FMA)
        self.label_12.setGeometry(QtCore.QRect(110, 420, 171, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(GUI_FMA)
        self.label_13.setGeometry(QtCore.QRect(40, 60, 121, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(GUI_FMA)
        self.label_14.setGeometry(QtCore.QRect(10, 590, 51, 17))
        self.label_14.setObjectName("label_14")
        self.lineEdit_4 = QtWidgets.QLineEdit(GUI_FMA)
        self.lineEdit_4.setGeometry(QtCore.QRect(60, 590, 120, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        #---------------------------------------------------
        
        #---------------------------------------------------
        self.retranslateUi(GUI_FMA)
        self.pushButton_6.clicked.connect(self.foto)
        self.pushButton_7.clicked.connect(self.video)
        self.pushButton_3.clicked.connect(self.posicioninicio)
        self.pushButton.clicked.connect(self.modomanual)
        self.pushButton_2.clicked.connect(self.modoautomatico)
        self.pushButton_4.clicked.connect(self.xbox)
        self.pushButton_5.clicked.connect(self.planear)
        self.lineEdit.editingFinished.connect(self.valorJ1)
        self.lineEdit_2.editingFinished.connect(self.valorJ2)
        self.lineEdit_3.editingFinished.connect(self.valorJ3)
        self.lineEdit_8.editingFinished.connect(self.valorJ4)
        self.lineEdit_9.editingFinished.connect(self.valorJ5)
        self.lineEdit_7.editingFinished.connect(self.valorJ6)
        self.lineEdit_6.editingFinished.connect(self.valorJ7)
        self.horizontalSlider.sliderMoved['int'].connect(self.J1)
        self.horizontalSlider_2.sliderMoved['int'].connect(self.J2)
        self.horizontalSlider_3.sliderMoved['int'].connect(self.J3)
        self.horizontalSlider_4.sliderMoved['int'].connect(self.J4)
        self.horizontalSlider_5.sliderMoved['int'].connect(self.J5)
        self.horizontalSlider_7.sliderMoved['int'].connect(self.J6)
        self.horizontalSlider_6.sliderMoved['int'].connect(self.J7)
        self.pushButton_14.clicked.connect(self.ON)
        self.pushButton_16.clicked.connect(self.OFF)
        self.pushButton_8.clicked.connect(self.T1)
        self.pushButton_11.clicked.connect(self.T2)
        self.pushButton_12.clicked.connect(self.T3)
        self.pushButton_9.clicked.connect(self.T4)
        self.pushButton_10.clicked.connect(self.T5)
        self.pushButton_13.clicked.connect(self.T6)
        QtCore.QMetaObject.connectSlotsByName(GUI_FMA)

        #---------------------------------------------------
        self.lineEdit.setText(str(self.M1))
        self.lineEdit_2.setText(str(self.M2))
        self.lineEdit_3.setText(str(self.M3))
        self.lineEdit_8.setText(str(self.M4))
        self.lineEdit_9.setText(str(self.M5))
        self.lineEdit_7.setText(str(self.M6))
        self.lineEdit_6.setText(str("0.0"))
        self.lineEdit_4.setText(str("Manual"))
        self.lineEdit_4.setText(str("Apagada"))
        #---------------------------------------------------

    def retranslateUi(self, GUI_FMA):
        _translate = QtCore.QCoreApplication.translate
        GUI_FMA.setWindowTitle(_translate("GUI_FMA", "Form"))
        self.pushButton.setText(_translate("GUI_FMA", "Modo Manual"))
        self.pushButton_2.setText(_translate("GUI_FMA", "Modo Automatico"))
        self.pushButton_3.setText(_translate("GUI_FMA", "Posicion de inicio"))
        self.label.setText(_translate("GUI_FMA", "J1"))
        self.label_2.setText(_translate("GUI_FMA", "J2"))
        self.label_3.setText(_translate("GUI_FMA", "J3"))
        self.label_4.setText(_translate("GUI_FMA", "J4"))
        self.label_5.setText(_translate("GUI_FMA", "J5"))
        self.label_6.setText(_translate("GUI_FMA", "J6"))
        self.label_7.setText(_translate("GUI_FMA", "J7"))
        self.pushButton_4.setText(_translate("GUI_FMA", "XBOX"))
        self.pushButton_5.setText(_translate("GUI_FMA", "PLANEAR"))
        self.pushButton_6.setText(_translate("GUI_FMA", "Foto"))
        self.pushButton_7.setText(_translate("GUI_FMA", "VIdeo"))
        self.label_8.setText(_translate("GUI_FMA", "<html><head/><body><p><span style=\" font-size:20pt;\">FILMMAKER ROBOT ARM</span></p></body></html>"))
        self.label_9.setText(_translate("GUI_FMA", "Control de posicion de motores"))
        self.pushButton_8.setText(_translate("GUI_FMA", "Trayectoria1"))
        self.pushButton_9.setText(_translate("GUI_FMA", "Trayectoria4"))
        self.pushButton_10.setText(_translate("GUI_FMA", "Trayectoria5"))
        self.pushButton_11.setText(_translate("GUI_FMA", "Trayectoria2"))
        self.pushButton_12.setText(_translate("GUI_FMA", "Trayectoria3"))
        self.pushButton_13.setText(_translate("GUI_FMA", "Trayectoria6"))
        self.pushButton_14.setText(_translate("GUI_FMA", "ON"))
        self.pushButton_16.setText(_translate("GUI_FMA", "OFF"))
        self.label_11.setText(_translate("GUI_FMA", "Camara control:"))
        self.label_12.setText(_translate("GUI_FMA", "Control de trayectorias:"))
        self.label_13.setText(_translate("GUI_FMA", "Camara viewer:"))
        self.label_14.setText(_translate("GUI_FMA", "Modo:"))
    
    def foto(self):
        self.Work.foto()
        

    def video(self):
        print ("Video")
    
    def ON(self):
        self.Work = Work()
        self.Work.start()
        self.Work.Imageupd.connect(self.Imageupd_slot)
    
    def Imageupd_slot(self, Image):
        self.label_10.setPixmap(QPixmap.fromImage(Image))
        
    def OFF(self):
        self.label_10.clear()
        self.Work.OFF()
    
    def posicioninicio(self):

        self.M1=0
        self.M2=0
        self.M3=1.4
        self.M4=0
        self.M5=0
        self.M6=1.59
        
        self.plano()

        print ("Posicion de inicio")

    def modomanual(self):
        self.M1= (self.horizontalSlider.value())
        self.lineEdit.setText(str(self.M1))
        self.M2= (self.horizontalSlider_2.value())
        self.lineEdit_2.setText(str(self.M2))
        self.M3= (self.horizontalSlider_3.value())
        self.lineEdit_3.setText(str(self.M3))
        self.M4= (self.horizontalSlider_4.value())
        self.lineEdit_8.setText(str(self.M4))
        self.M5= (self.horizontalSlider_5.value())
        self.lineEdit_9.setText(str(self.M5))
        self.M6= (self.horizontalSlider_7.value())
        self.lineEdit_7.setText(str(self.M6))
        self.xbox_status=0
        self.lineEdit_4.setText(str("Manual"))
        print(self.M1)
        print(self.M2)
        print(self.M3)
        print(self.M4)
        print(self.M5)
        print(self.M6)
        print ("Modo manual_GUI")
    
    def xbox(self):
        self.M1= (self.horizontalSlider.value())
        self.lineEdit.setText(str(self.M1))
        self.M2= (self.horizontalSlider_2.value())
        self.lineEdit_2.setText(str(self.M2))
        self.M3= (self.horizontalSlider_3.value())
        self.lineEdit_3.setText(str(self.M3))
        self.M4= (self.horizontalSlider_4.value())
        self.lineEdit_8.setText(str(self.M4))
        self.M5= (self.horizontalSlider_5.value())
        self.lineEdit_9.setText(str(self.M5))
        self.M6= (self.horizontalSlider_7.value())
        self.lineEdit_7.setText(str(self.M6))
        self.xbox_status=1
        self.lineEdit_4.setText(str("Control XBOX"))
        print(self.M1)
        print(self.M2)
        print(self.M3)
        print(self.M4)
        print(self.M5)
        print(self.M6)
        print ("MODO_MANUAL_XBOX")
    
    def modoautomatico(self):
        self.xbox_status=2
        self.lineEdit_4.setText(str("Automatico"))
        print ("Modo automatico")

    def planear(self):
        self.plano()
        print ("PLANEAR") 

    def valorJ1(self):
        self.iM1=(self.lineEdit.text())
        self.M1=float(self.iM1)
        self.horizontalSlider.setValue(self.M1)
        print(self.M1)
        print ("J1")       

    def valorJ2(self):
        self.iM2=(self.lineEdit_2.text())
        self.M2=float(self.iM2)
        self.horizontalSlider_2.setValue(self.M2)
        print(self.M2)
        print ("J2")       

    def valorJ3(self):
        self.iM3=(self.lineEdit_3.text())
        self.M3=float(self.iM3)
        self.horizontalSlider_3.setValue(self.M3)
        print(self.M3)
        print ("J3")  

    def valorJ4(self):
        self.iM4=(self.lineEdit_8.text())
        self.M4=float(self.iM4)
        self.horizontalSlider_4.setValue(self.M4)
        print(self.M4)
        print ("J4")  

    def valorJ5(self):
        self.iM5=(self.lineEdit_9.text())
        self.M5=float(self.iM5)
        self.horizontalSlider_5.setValue(self.M5)
        print(self.M5)  
        print ("J5")  

    def valorJ6(self):
        self.iM6=(self.lineEdit_7.text())
        self.M6=float(self.iM6)
        self.horizontalSlider_7.setValue(self.M6)
        print(self.M6) 
        print ("J6")  

    def valorJ7(self):
        #self.iM67=int(self.lineEdit_6.text())
        #self.M71=float(self.iM61)/64.35
        #print(self.M61) 
        print ("J7")  

    def J1(self):
        float (self.M1)
        self.M1= (self.horizontalSlider.value())
        self.lineEdit.setText(str(self.horizontalSlider.value()))

    def J2(self):
        float (self.M2)
        self.M2= (self.horizontalSlider_2.value())
        self.lineEdit_2.setText(str(self.M2))

    def J3(self):
        float (self.M3)
        self.M3= (self.horizontalSlider_3.value())
        self.lineEdit_3.setText(str(self.M3))

    def J4(self):
        float (self.M4)
        self.M4= (self.horizontalSlider_4.value())
        self.lineEdit_8.setText(str(self.M4))

    def J5(self):
        float (self.M5)
        self.M5= (self.horizontalSlider_5.value())
        self.lineEdit_9.setText(str(self.M5))

    def J6(self):
        float (self.M6)
        self.M6= (self.horizontalSlider_7.value())
        self.lineEdit_7.setText(str(self.M6))

    def J7(self):
        print("FUERA DE SERVICIO")
        print(self.xbox_status)
    #    float (self.M7)
    #    self.M7= (self.horizontalSlider_7.value())
    #    self.lineEdit_6.setText(str(self.M7))
    
    def plano(self):
        
        print('Entre a la funcion planear')
        # We can get the joint values from the group and adjust some of the values:
        self.joint_goal = self.move_group.get_current_joint_values()
        print(self.joint_goal)

        # joint_goal[1] = 0
        # joint_goal[2] = 0
        # joint_goal[3] = 0
        # joint_goal[4] = 0
        # joint_goal[5] = 0
        # joint_goal[6] = 0
       
        #cambiar joint values
        self.joint_goal[0] = float(self.M1)/68    #  // radians
        self.joint_goal[1] = float(self.M2)/65    #  // radians-0.6   1.37
        self.joint_goal[2] = float(self.M3)/57.6  #  // radians 0 2.5
        self.joint_goal[3] = float(self.M4)/61.11 #  // radians -2.7 
        self.joint_goal[4] = float(self.M5)/57.78 #  // radians 1.8
        self.joint_goal[5] = float(self.M6)/64.35 #  // radians 2.3
        
       
        # The go command can be called with joint values, poses, or without any
        # parameters if you have already set the pose or joint target for the group
        self.move_group.set_joint_value_target(self.joint_goal)
        self.plan = self.move_group.go( wait=True)
        #plan = move_group.go(joint_goal, wait=True)
        print("after planning")
        # Calling ``stop()`` ensures that there is no residual movement
        self.move_group.stop()
        #joint_goal[0] =1.57  #;  // radians
        #joint_goal[1] = 0.0 #;  // radians
        #joint_goal[2] = 0.0 #;  // radians
        #joint_goal[3] = 0.0 #  // radians
        #joint_goal[4] = 0.0 #;  // radians
        #joint_goal[5] = 0.0 #;  // radians
        #move_group.execute(plan,  wait=True)
        #move_group.set_joint_value_target(joint_goal)
        # plan = move_group.go( wait=True)
        rospy.sleep(1)                                                 
        print("end")
    
    def control(self,data):

        self.A=data.buttons[0]  #Obtencion de los datos de los botones del control xbox
        self.B=data.buttons[1]
        self.X=data.buttons[2]
        self.Y=data.buttons[3]
        self.RB=data.buttons[5]
        self.LB=data.buttons[4]
        self.UD=data.axes[7]
        self.DI=data.axes[6]
        self.SQ=data.buttons[6]
        print(self.xbox_status)

        if self.xbox_status==1:

            if self.A==1 and self.DI==1 and self.M1<=2.0*68:           #Condiciones de los botones del xbox para 
                self.M1+=0.2*68  #;  // radians   #establecer cuantos radianes se movera el robot. 
                self.lineEdit.setText(str(self.M1))
                self.horizontalSlider.setValue(self.M1)
                print(self.M1)
                print("xbox_Control")
                self.plano()
        
            if self.A==1 and self.DI==-1 :
                self.M1+=-0.2*68  #;  // radians
                self.lineEdit.setText(str(self.M1))
                self.horizontalSlider.setValue(self.M1)
                print("xbox_Control")
                self.plano()
            
            if self.B==1 and self.UD==1 :
                self.M2-=0.1*65  #;  // radians
                self.lineEdit_2.setText(str(self.M2))
                self.horizontalSlider_2.setValue(self.M2)
                print("xbox_Control")
                self.plano()

            if self.B==1 and self.UD==-1 :
                self.M2+=0.1*65  #;  // radians
                self.lineEdit_2.setText(str(self.M2))
                self.horizontalSlider_2.setValue(self.M2)
                print("xbox_Control")
                self.plano()

            if self.Y==1 and self.UD==1 and self.M3>=0.1 :
                self.M3-=0.1*57.6 #;  // radians
                self.lineEdit_3.setText(str(self.M3))
                self.horizontalSlider_3.setValue(self.M3)
                print("xbox_Control")
                self.plano()

            if self.Y==1 and self.UD==-1 :
                self.M3+=0.1*57.6  #;  // radians
                self.lineEdit_3.setText(str(self.M3))
                self.horizontalSlider_3.setValue(self.M3)
                print("xbox_Control")
                self.plano()
            
            if self.X==1 and self.DI==1 :
                self.M4+=0.1*61.11 #;  // radians
                self.lineEdit_8.setText(str(self.M4))
                self.horizontalSlider_4.setValue(self.M4)
                print("xbox_Control")
                self.plano()

            if self.X==1 and self.DI==-1 :
                self.M4+=-0.1*61.11  #;  // radians
                self.lineEdit_8.setText(str(self.M4))
                self.horizontalSlider_4.setValue(self.M4)
                print("xbox_Control")
                self.plano()

            if self.RB==1 and self.UD==1 :
                self.M5-=0.1*57.78  #;  // radians
                self.lineEdit_9.setText(str(self.M5))
                self.horizontalSlider_5.setValue(self.M5)
                print("xbox_Control")
                self.plano()

            if self.RB==1 and self.UD==-1 :
                self.M5+=0.1*57.78  #;  // radians
                self.lineEdit_9.setText(str(self.M5))
                self.horizontalSlider_5.setValue(self.M5)
                print("xbox_Control")
                self.plano()

            if self.LB==1 and self.DI==1 :
                M6+=0.3*64.35  #;  // radians
                self.lineEdit_7.setText(str(self.M6))
                self.horizontalSlider_7.setValue(self.M6)
                print("xbox_Control")
                self.plano()

            if self.LB==1 and self.DI==-1 :
                self.M6+=-0.3*64.35  #;  // radians
                self.lineEdit_7.setText(str(self.M6))
                self.horizontalSlider_7.setValue(self.M6)
                print("xbox_Control")
                self.plano()

            if self.SQ==1 and self.A==1:
                xbox_status=0
                print("MODO_GUI")

            if self.SQ==1 and self.B==1:
                xbox_status=1
                print("MODO_CONTROL_XBOX")
            
            if self.SQ==1 and self.Y==1:
                self.counter=0
                xbox_status=2
                print("MODO_AUTOMATICO") 
            
            if self.SQ==1 and self.X==1:
                self.counter=0
                xbox_status=3
                print(xbox_status) 
            
            if self.SQ==1 and self.RB==1:
                self.counter=0
                xbox_status=4
                print(xbox_status) 

            if self.SQ==1 and self.LB==1:
                self.counter=0
                xbox_status=5
                print(xbox_status) 
            #if move==1:
            # move=0
            # planear()

class Work(QThread):
    img_counter=0
    Imageupd = pyqtSignal(QImage)
    def run(self):
        self.hilo_corriendo = True
        cap = cv2.VideoCapture(0)
        while self.hilo_corriendo:
            ret, self.frame = cap.read()
            if ret:
                Image = cv2.cvtColor(self.frame, cv2.COLOR_BGR2RGB)
                flip = cv2.flip(Image, 1)
                convertir_QT = QImage(flip.data, flip.shape[1], flip.shape[0], QImage.Format_RGB888)
                pic = convertir_QT.scaled(640, 240, Qt.KeepAspectRatio)
                self.Imageupd.emit(pic)
    def OFF(self):
        self.hilo_corrienself.img_counterdo = False
        self.quit()
    
    def foto(self):
    
        self.img_name = "imagen_{}.png".format(self.img_counter) 
        cv2.imwrite(self.img_name, self.frame)
        print("{} written!".format(self.img_name)) 
        self.img_counter += 1  
        print ("Video")

if __name__ == "__main__":
    import sys
    
    moveit_commander.roscpp_initialize(sys.argv)
    rospy.init_node('robot_plan', anonymous=True)
    rospy.loginfo("robot_plan")

    app = QtWidgets.QApplication(sys.argv)
    GUI_FMA = QtWidgets.QWidget()
    ui = Ui_GUI_FMA()
    ui.setupUi(GUI_FMA)
    GUI_FMA.show()
    sys.exit(app.exec_())
