# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MAUTOMATICO.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import rospy
import os
from std_msgs.msg import Float32

class Ui_AFOTOVIDEO(object):
    
    def talker(self):
        
        pub = rospy.Publisher('Capturar' , Float32, queue_size = 1)
        rospy.loginfo(self.cap)
        pub.publish(self.cap)
            
    def talker1(self):
        
        pub = rospy.Publisher('VideoOn' , Float32, queue_size = 1)
        rospy.loginfo(self.von)
        pub.publish(self.von)
    
    def talker2(self):
        
        pub = rospy.Publisher('VideoOff' , Float32, queue_size = 1)
        rospy.loginfo(self.voff)
        pub.publish(self.voff)   
    def setupUi(self, AFOTOVIDEO):
        AFOTOVIDEO.setObjectName("AFOTOVIDEO")
        AFOTOVIDEO.resize(193, 101)
        self.label = QtWidgets.QLabel(AFOTOVIDEO)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 19))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"DejaVu Sans\";")
        self.label.setObjectName("label")
        self.label_27 = QtWidgets.QLabel(AFOTOVIDEO)
        self.label_27.setGeometry(QtCore.QRect(120, 40, 61, 16))
        self.label_27.setObjectName("label_27")
        self.pushButton_20 = QtWidgets.QPushButton(AFOTOVIDEO)
        self.pushButton_20.setGeometry(QtCore.QRect(100, 60, 41, 31))
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_23 = QtWidgets.QLabel(AFOTOVIDEO)
        self.label_23.setGeometry(QtCore.QRect(10, 40, 91, 17))
        self.label_23.setObjectName("label_23")
        self.pushButton_22 = QtWidgets.QPushButton(AFOTOVIDEO)
        self.pushButton_22.setGeometry(QtCore.QRect(10, 60, 81, 31))
        self.pushButton_22.setStyleSheet("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_21 = QtWidgets.QPushButton(AFOTOVIDEO)
        self.pushButton_21.setGeometry(QtCore.QRect(140, 60, 41, 31))
        self.pushButton_21.setObjectName("pushButton_21")

        self.retranslateUi(AFOTOVIDEO)
        self.pushButton_22.clicked.connect(self.capturar)
        self.pushButton_20.clicked.connect(self.vstart)
        self.pushButton_21.clicked.connect(self.vstop)
        QtCore.QMetaObject.connectSlotsByName(AFOTOVIDEO)

    def retranslateUi(self, AFOTOVIDEO):
        _translate = QtCore.QCoreApplication.translate
        AFOTOVIDEO.setWindowTitle(_translate("AFOTOVIDEO", "Form"))
        self.label.setText(_translate("AFOTOVIDEO", "  MODO AUTOMATICO"))
        self.label_27.setText(_translate("AFOTOVIDEO", "Video:"))
        self.pushButton_20.setText(_translate("AFOTOVIDEO", "ON"))
        self.label_23.setText(_translate("AFOTOVIDEO", "Fotografía:"))
        self.pushButton_22.setText(_translate("AFOTOVIDEO", "Capturar"))
        self.pushButton_21.setText(_translate("AFOTOVIDEO", "OFF"))
    
    def capturar(self):
        self.cap=1
        self.talker()
        rospy.sleep(0.5)
        self.cap=0
        self.talker()
        print("capturar")

    def vstart(self):
        self.von=1
        self.talker1()
        rospy.sleep(0.5)
        self.von=0
        self.talker1()
        print("videoON")

    def vstop(self):
        self.voff=1
        self.talker2()
        rospy.sleep(0.5)
        self.voff=0
        self.talker2()
        print("videoOFF")


if __name__ == "__main__":
    import sys
    rospy.init_node('MA' , anonymous = False)
    app = QtWidgets.QApplication(sys.argv)
    AFOTOVIDEO = QtWidgets.QWidget()
    ui = Ui_AFOTOVIDEO()
    ui.setupUi(AFOTOVIDEO)
    AFOTOVIDEO.show()
    sys.exit(app.exec_())
