# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MODOCENTRADO.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from T1C import Ui_T1C
from T2C import Ui_T2C
from T3C import Ui_T3C
import rospy
import os
from std_msgs.msg import Float32

class Ui_CENTRAR(object):
    
    def talker(self):
        
        pub = rospy.Publisher('Capturar' , Float32, queue_size = 1)
        rospy.loginfo(self.cap)
        pub.publish(self.cap)
            
    def talker1(self):
        
        pub = rospy.Publisher('VideoOn' , Float32, queue_size = 1)
        rospy.loginfo(self.von)
        pub.publish(self.von)
    
    def talker2(self):
        
        pub = rospy.Publisher('VideoOff' , Float32, queue_size = 1)
        rospy.loginfo(self.voff)
        pub.publish(self.voff)   
    def t1(self):

        self.window=QtWidgets.QWidget()
        self.ui= Ui_T1C()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def t2(self):

        self.window=QtWidgets.QWidget()
        self.ui= Ui_T2C()
        self.ui.setupUi(self.window)
        self.window.show()
    def t3(self):

        self.window=QtWidgets.QWidget()
        self.ui= Ui_T3C()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, CENTRAR):
        CENTRAR.setObjectName("CENTRAR")
        CENTRAR.resize(195, 228)
        self.label = QtWidgets.QLabel(CENTRAR)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 19))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"DejaVu Sans\";")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(CENTRAR)
        self.pushButton.setGeometry(QtCore.QRect(40, 40, 111, 27))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(CENTRAR)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 70, 111, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(CENTRAR)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 100, 111, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(CENTRAR)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 130, 51, 27))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(CENTRAR)
        self.pushButton_5.setGeometry(QtCore.QRect(100, 130, 51, 27))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_27 = QtWidgets.QLabel(CENTRAR)
        self.label_27.setGeometry(QtCore.QRect(120, 170, 61, 16))
        self.label_27.setObjectName("label_27")
        self.pushButton_20 = QtWidgets.QPushButton(CENTRAR)
        self.pushButton_20.setGeometry(QtCore.QRect(100, 190, 41, 31))
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_23 = QtWidgets.QLabel(CENTRAR)
        self.label_23.setGeometry(QtCore.QRect(10, 170, 91, 17))
        self.label_23.setObjectName("label_23")
        self.pushButton_22 = QtWidgets.QPushButton(CENTRAR)
        self.pushButton_22.setGeometry(QtCore.QRect(10, 190, 81, 31))
        self.pushButton_22.setStyleSheet("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_21 = QtWidgets.QPushButton(CENTRAR)
        self.pushButton_21.setGeometry(QtCore.QRect(140, 190, 41, 31))
        self.pushButton_21.setObjectName("pushButton_21")

        self.retranslateUi(CENTRAR)
        self.pushButton.clicked.connect(self.t1)
        self.pushButton_2.clicked.connect(self.t2)
        self.pushButton_3.clicked.connect(self.t3)
        self.pushButton_5.clicked.connect(self.stop)
        self.pushButton_4.clicked.connect(self.start)
        self.pushButton_22.clicked.connect(self.capturar)
        self.pushButton_20.clicked.connect(self.vstart)
        self.pushButton_21.clicked.connect(self.vstop)
        QtCore.QMetaObject.connectSlotsByName(CENTRAR)

    def retranslateUi(self, CENTRAR):
        _translate = QtCore.QCoreApplication.translate
        CENTRAR.setWindowTitle(_translate("CENTRAR", "Form"))
        self.label.setText(_translate("CENTRAR", "MODO CENTRADO"))
        self.pushButton.setText(_translate("CENTRAR", "Trayectoria1"))
        self.pushButton_2.setText(_translate("CENTRAR", "Trayectoria2"))
        self.pushButton_3.setText(_translate("CENTRAR", "Trayectoria3"))
        self.pushButton_4.setText(_translate("CENTRAR", "Start"))
        self.pushButton_5.setText(_translate("CENTRAR", "Stop"))
        self.label_27.setText(_translate("CENTRAR", "Video:"))
        self.pushButton_20.setText(_translate("CENTRAR", "ON"))
        self.label_23.setText(_translate("CENTRAR", "Fotografía:"))
        self.pushButton_22.setText(_translate("CENTRAR", "Capturar"))
        self.pushButton_21.setText(_translate("CENTRAR", "OFF"))
        self.cap=0
        self.voff=0
        self.von=0

    def stop(self):
        print("stop")

    def start(self):
        os.system("gnome-terminal -e 'bash -c \"python centrado2.py\"'")

    def capturar(self):
        self.cap=1
        self.talker()
        rospy.sleep(0.5)
        self.cap=0
        self.talker()
        print("capturar")

    def vstart(self):
        self.von=1
        self.talker1()
        rospy.sleep(0.5)
        self.von=0
        self.talker1()
        print("videoON")

    def vstop(self):
        self.voff=1
        self.talker2()
        rospy.sleep(0.5)
        self.voff=0
        self.talker2()
        print("videoOFF")

if __name__ == "__main__":
    import sys
    rospy.init_node('MC' , anonymous = False)
    app = QtWidgets.QApplication(sys.argv)
    CENTRAR = QtWidgets.QWidget()
    ui = Ui_CENTRAR()
    ui.setupUi(CENTRAR)
    CENTRAR.show()
    sys.exit(app.exec_())
