# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'T1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import copy
import rospy
import moveit_commander
import moveit_msgs.msg
import geometry_msgs.msg
from math import pi
from std_msgs.msg import String, Float32
from moveit_commander.conversions import pose_to_list
from geometry_msgs.msg import Twist
from sensor_msgs.msg import Joy
from Trayectoria1 import *
import pickle

global M11,M21,M31,M41,M51,M61,M12,M22,M32,M42,M52,M62,M13,M23,M33,M43,M53,M63
class Ui_trayectoria1(object):
    def setupUi(self, trayectoria1):
        self.robot = moveit_commander.RobotCommander()
        self.scene = moveit_commander.PlanningSceneInterface()
        self.group_name = "manipulator"
        self.move_group = moveit_commander.MoveGroupCommander(self.group_name)

        self.planning_frame = self.move_group.get_planning_frame()
        print("============ Planning frame: %s" % self.planning_frame)

        # We can also print the name of the end-effector link for this group:
        self.eef_link = self.move_group.get_end_effector_link()
        print("============ End effector link: %s" % self.eef_link)

        # We can get a list of all the groups in the robot:
        self.group_names = self.robot.get_group_names()
        print("============ Available Planning Groups:", self.robot.get_group_names())

        # Sometimes for debugging it is useful to print the entire state of the
        # robot:
        print("============ Printing robot state")
        print(self.robot.get_current_state())
        print("")
        
        self.M1=0.0
        self.M2=0.0
        self.M3=0.0
        self.M4=0.0
        self.M5=0.0
        self.M6=0.0

        self.M11=0.0
        self.M21=0.0
        self.M31=0.0
        self.M41=0.0
        self.M51=0.0
        self.M61=0.0

        self.M12=0.0
        self.M22=0.0
        self.M32=0.0
        self.M42=0.0
        self.M52=0.0
        self.M62=0.0

        self.M13=0.0
        self.M23=0.0
        self.M33=0.0
        self.M43=0.0
        self.M53=0.0
        self.M63=0.0

        trayectoria1.setObjectName("trayectoria1")
        trayectoria1.resize(333, 373)
        self.pushButton = QtWidgets.QPushButton(trayectoria1)
        self.pushButton.setGeometry(QtCore.QRect(130, 10, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(trayectoria1)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 21, 20))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(trayectoria1)
        self.label.setGeometry(QtCore.QRect(20, 70, 21, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(trayectoria1)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 21, 21))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(trayectoria1)
        self.label_6.setGeometry(QtCore.QRect(20, 270, 21, 20))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(trayectoria1)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 21, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(trayectoria1)
        self.label_5.setGeometry(QtCore.QRect(20, 230, 21, 20))
        self.label_5.setObjectName("label_5")
        self.lineEdit_7 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_7.setGeometry(QtCore.QRect(40, 270, 61, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_8.setGeometry(QtCore.QRect(40, 190, 61, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit.setGeometry(QtCore.QRect(40, 70, 61, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 150, 61, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_9 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_9.setGeometry(QtCore.QRect(40, 230, 61, 25))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_2 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 110, 61, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_13 = QtWidgets.QLabel(trayectoria1)
        self.label_13.setGeometry(QtCore.QRect(40, 50, 51, 17))
        self.label_13.setObjectName("label_13")
        self.pushButton_15 = QtWidgets.QPushButton(trayectoria1)
        self.pushButton_15.setGeometry(QtCore.QRect(50, 300, 41, 21))
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_7 = QtWidgets.QLabel(trayectoria1)
        self.label_7.setGeometry(QtCore.QRect(120, 230, 21, 20))
        self.label_7.setObjectName("label_7")
        self.lineEdit_10 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_10.setGeometry(QtCore.QRect(140, 190, 61, 25))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_14 = QtWidgets.QLabel(trayectoria1)
        self.label_14.setGeometry(QtCore.QRect(140, 50, 51, 17))
        self.label_14.setObjectName("label_14")
        self.label_8 = QtWidgets.QLabel(trayectoria1)
        self.label_8.setGeometry(QtCore.QRect(120, 190, 21, 20))
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 110, 61, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 150, 61, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_11 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_11.setGeometry(QtCore.QRect(140, 230, 61, 25))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pushButton_16 = QtWidgets.QPushButton(trayectoria1)
        self.pushButton_16.setGeometry(QtCore.QRect(150, 300, 41, 21))
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_9 = QtWidgets.QLabel(trayectoria1)
        self.label_9.setGeometry(QtCore.QRect(120, 270, 21, 20))
        self.label_9.setObjectName("label_9")
        self.lineEdit_6 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_6.setGeometry(QtCore.QRect(140, 70, 61, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_10 = QtWidgets.QLabel(trayectoria1)
        self.label_10.setGeometry(QtCore.QRect(120, 110, 21, 21))
        self.label_10.setObjectName("label_10")
        self.lineEdit_12 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_12.setGeometry(QtCore.QRect(140, 270, 61, 25))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_11 = QtWidgets.QLabel(trayectoria1)
        self.label_11.setGeometry(QtCore.QRect(120, 70, 21, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(trayectoria1)
        self.label_12.setGeometry(QtCore.QRect(120, 150, 21, 20))
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(trayectoria1)
        self.label_15.setGeometry(QtCore.QRect(230, 190, 21, 20))
        self.label_15.setObjectName("label_15")
        self.lineEdit_13 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_13.setGeometry(QtCore.QRect(250, 110, 61, 25))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_14.setGeometry(QtCore.QRect(250, 70, 61, 25))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_16 = QtWidgets.QLabel(trayectoria1)
        self.label_16.setGeometry(QtCore.QRect(230, 110, 21, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(trayectoria1)
        self.label_17.setGeometry(QtCore.QRect(230, 70, 21, 20))
        self.label_17.setObjectName("label_17")
        self.lineEdit_15 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_15.setGeometry(QtCore.QRect(250, 270, 61, 25))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_18 = QtWidgets.QLabel(trayectoria1)
        self.label_18.setGeometry(QtCore.QRect(250, 50, 51, 17))
        self.label_18.setObjectName("label_18")
        self.lineEdit_16 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_16.setGeometry(QtCore.QRect(250, 190, 61, 25))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_17.setGeometry(QtCore.QRect(250, 150, 61, 25))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_19 = QtWidgets.QLabel(trayectoria1)
        self.label_19.setGeometry(QtCore.QRect(230, 230, 21, 20))
        self.label_19.setObjectName("label_19")
        self.lineEdit_18 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_18.setGeometry(QtCore.QRect(250, 230, 61, 25))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_20 = QtWidgets.QLabel(trayectoria1)
        self.label_20.setGeometry(QtCore.QRect(230, 270, 21, 20))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(trayectoria1)
        self.label_21.setGeometry(QtCore.QRect(230, 150, 21, 20))
        self.label_21.setObjectName("label_21")
        self.pushButton_17 = QtWidgets.QPushButton(trayectoria1)
        self.pushButton_17.setGeometry(QtCore.QRect(260, 300, 41, 21))
        self.pushButton_17.setObjectName("pushButton_17")
        self.lineEdit_19 = QtWidgets.QLineEdit(trayectoria1)
        self.lineEdit_19.setGeometry(QtCore.QRect(190, 340, 61, 25))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_22 = QtWidgets.QLabel(trayectoria1)
        self.label_22.setGeometry(QtCore.QRect(10, 340, 181, 17))
        self.label_22.setObjectName("label_22")
        
        self.retranslateUi(trayectoria1)
        self.pushButton.clicked.connect(self.planeo)
        self.pushButton_15.clicked.connect(self.set1)
        self.pushButton_16.clicked.connect(self.set2)
        self.pushButton_17.clicked.connect(self.set3)
        self.lineEdit.editingFinished.connect(self.P1J1)
        self.lineEdit_2.editingFinished.connect(self.P1J2)
        self.lineEdit_3.editingFinished.connect(self.P1J3)
        self.lineEdit_8.editingFinished.connect(self.P1J4)
        self.lineEdit_9.editingFinished.connect(self.P1J5)
        self.lineEdit_7.editingFinished.connect(self.P1J6)
        self.lineEdit_6.editingFinished.connect(self.P2J1)
        self.lineEdit_4.editingFinished.connect(self.P2J2)
        self.lineEdit_5.editingFinished.connect(self.P2J3)
        self.lineEdit_10.editingFinished.connect(self.P2J4)
        self.lineEdit_11.editingFinished.connect(self.P2J5)
        self.lineEdit_12.editingFinished.connect(self.P2J6)
        self.lineEdit_14.editingFinished.connect(self.P3J1)
        self.lineEdit_13.editingFinished.connect(self.P3J2)
        self.lineEdit_17.editingFinished.connect(self.P3J3)
        self.lineEdit_16.editingFinished.connect(self.P3J4)
        self.lineEdit_18.editingFinished.connect(self.P3J5)
        self.lineEdit_15.editingFinished.connect(self.P3J6)
        self.lineEdit_19.editingFinished.connect(self.Repeticion)
        QtCore.QMetaObject.connectSlotsByName(trayectoria1)

    def retranslateUi(self, trayectoria1):
        _translate = QtCore.QCoreApplication.translate
        trayectoria1.setWindowTitle(_translate("trayectoria1", "Form"))
        self.pushButton.setText(_translate("trayectoria1", "Planear"))
        self.label_3.setText(_translate("trayectoria1", "J3"))
        self.label.setText(_translate("trayectoria1", "J1"))
        self.label_2.setText(_translate("trayectoria1", "J2"))
        self.label_6.setText(_translate("trayectoria1", "J6"))
        self.label_4.setText(_translate("trayectoria1", "J4"))
        self.label_5.setText(_translate("trayectoria1", "J5"))
        self.label_13.setText(_translate("trayectoria1", "Point1:"))
        self.pushButton_15.setText(_translate("trayectoria1", "SET"))
        self.label_7.setText(_translate("trayectoria1", "J5"))
        self.label_14.setText(_translate("trayectoria1", "Point2:"))
        self.label_8.setText(_translate("trayectoria1", "J4"))
        self.pushButton_16.setText(_translate("trayectoria1", "SET"))
        self.label_9.setText(_translate("trayectoria1", "J6"))
        self.label_10.setText(_translate("trayectoria1", "J2"))
        self.label_11.setText(_translate("trayectoria1", "J1"))
        self.label_12.setText(_translate("trayectoria1", "J3"))
        self.label_15.setText(_translate("trayectoria1", "J4"))
        self.label_16.setText(_translate("trayectoria1", "J2"))
        self.label_17.setText(_translate("trayectoria1", "J1"))
        self.label_18.setText(_translate("trayectoria1", "Point3:"))
        self.label_19.setText(_translate("trayectoria1", "J5"))
        self.label_20.setText(_translate("trayectoria1", "J6"))
        self.label_21.setText(_translate("trayectoria1", "J3"))
        self.pushButton_17.setText(_translate("trayectoria1", "SET"))
        self.label_22.setText(_translate("trayectoria1", "Cantidad de repeticiones:"))
        #self.read()
        self.lineEdit_19.setText("1")
        self.repetir=int(self.lineEdit_19.text())
        
        self.M11=M11
        self.M21=M21
        self.M31=M31
        self.M41=M11
        self.M51=M21
        self.M61=M31
        self.M12=M12
        self.M22=M22
        self.M32=M32
        self.M42=M42
        self.M52=M52
        self.M62=M62
        self.M13=M13
        self.M23=M23
        self.M33=M33
        self.M43=M43
        self.M53=M53
        self.M63=M63

        print(float(self.M11))
        print(float(self.M21))
    def planeo(self):
        self.printear()
        while self.repetir!=0:
            print ("Foto")
            self.M1=float(self.M11)   #  // radians
            self.M2=float(self.M21 )    #  // radians-0.6   1.37
            self.M3=float(self.M31)   #  // radians 0 2.5
            self.M4=float(self.M41)  #  // radians -2.7 
            self.M5=float(self.M51)
            self.M6=float(self.M61 )
            self.plano()

            self.M1=float(self.M12)   #  // radians
            self.M2=float(self.M22)    #  // radians-0.6   1.37
            self.M3=float(self.M32)   #  // radians 0 2.5
            self.M4=float(self.M42)  #  // radians -2.7 
            self.M5=float(self.M52)
            self.M6=float(self.M62) 
            self.plano()

            self.M1=float(self.M13)  #  // radians
            self.M2=float(self.M23)     #  // radians-0.6   1.37
            self.M3=float(self.M33)   #  // radians 0 2.5
            self.M4=float(self.M43)  #  // radians -2.7 
            self.M5=float(self.M53)
            self.M6=float(self.M63)
            self.plano()
            self.repetir-=1
        self.repetir=int(self.lineEdit_19.text())

    def set1(self):
        
        self.joint_goal = self.move_group.get_current_joint_values() 
        self.M11=self.joint_goal[0]    #  // radians
        self.M21=self.joint_goal[1]     #  // radians-0.6   1.37
        self.M31=self.joint_goal[2]   #  // radians 0 2.5
        self.M41=self.joint_goal[3]  #  // radians -2.7 
        self.M51=self.joint_goal[4] 
        self.M61=self.joint_goal[5] 

        self.iM11=int(self.joint_goal[0]*68)    #  // radians
        self.iM21=int(self.joint_goal[1]*65)      #  // radians-0.6   1.37
        self.iM31=int(self.joint_goal[2]*57.6)    #  // radians 0 2.5
        self.iM41=int(self.joint_goal[3]*61.11)  #  // radians -2.7 
        self.iM51=int(self.joint_goal[4]*57.78)  
        self.iM61=int(self.joint_goal[5]*64.35) 
    
        self.lineEdit.setText(str(self.iM11))
        self.lineEdit_2.setText(str(self.iM21 ))
        self.lineEdit_3.setText(str(self.iM31 ))
        self.lineEdit_8.setText(str(self.iM41 ))
        self.lineEdit_9.setText(str(self.iM51))
        self.lineEdit_7.setText(str(self.iM61 ))
        self.save()
        self.printear()

    def Repeticion(self):
        self.repetir=int(self.lineEdit_19.text())
        print("Repetir")
        self.printear()

    def set2(self):
        self.joint_goal = self.move_group.get_current_joint_values() 
        self.M12=self.joint_goal[0]    #  // radians
        self.M22=self.joint_goal[1]     #  // radians-0.6   1.37
        self.M32=self.joint_goal[2]   #  // radians 0 2.5
        self.M42=self.joint_goal[3]  #  // radians -2.7 
        self.M52=self.joint_goal[4] 
        self.M62=self.joint_goal[5] 

        self.iM12=int(self.joint_goal[0]*68)    #  // radians
        self.iM22=int(self.joint_goal[1]*65)      #  // radians-0.6   1.37
        self.iM32=int(self.joint_goal[2]*57.6)    #  // radians 0 2.5
        self.iM42=int(self.joint_goal[3]*61.11)  #  // radians -2.7 
        self.iM52=int(self.joint_goal[4]*57.78)  
        self.iM62=int(self.joint_goal[5]*64.35) 
    
        self.lineEdit_6.setText(str(self.iM12))
        self.lineEdit_4.setText(str(self.iM22 ))
        self.lineEdit_5.setText(str(self.iM32 ))
        self.lineEdit_10.setText(str(self.iM42 ))
        self.lineEdit_11.setText(str(self.iM52))
        self.lineEdit_12.setText(str(self.iM62 ))
        print ("set2")
    
    def set3(self):
        
        self.joint_goal = self.move_group.get_current_joint_values() 
        self.M13=self.joint_goal[0]    #  // radians
        self.M23=self.joint_goal[1]     #  // radians-0.6   1.37
        self.M33=self.joint_goal[2]   #  // radians 0 2.5
        self.M43=self.joint_goal[3]  #  // radians -2.7 
        self.M53=self.joint_goal[4] 
        self.M63=self.joint_goal[5] 

        self.iM13=int(self.joint_goal[0]*68)    #  // radians
        self.iM23=int(self.joint_goal[1]*65)      #  // radians-0.6   1.37
        self.iM33=int(self.joint_goal[2]*57.6)    #  // radians 0 2.5
        self.iM43=int(self.joint_goal[3]*61.11)  #  // radians -2.7 
        self.iM53=int(self.joint_goal[4]*57.78)  
        self.iM63=int(self.joint_goal[5]*64.35) 
    
        self.lineEdit_14.setText(str(self.iM13))
        self.lineEdit_13.setText(str(self.iM23 ))
        self.lineEdit_17.setText(str(self.iM33 ))
        self.lineEdit_16.setText(str(self.iM43 ))
        self.lineEdit_18.setText(str(self.iM53))
        self.lineEdit_15.setText(str(self.iM63 ))
        print ("Set3")
    
    def P1J1(self):
        print ("Modo manual_GUI")
    
    def P1J2(self):
        print ("MODO_MANUAL_XBOX")

    def P1J3(self):
        print ("MODO_MANUAL_XBOX")
    
    def P1J4(self):
        print ("MODO_MANUAL_XBOX")

    def P1J5(self):
        print ("MODO_MANUAL_XBOX")  
    
    def P1J6(self):
        print ("MODO_MANUAL_XBOX")  
    
     
    def P2J1(self):
        print ("Modo manual_GUI")
    
    def P2J2(self):
        print ("MODO_MANUAL_XBOX")

    def P2J3(self):
        print ("MODO_MANUAL_XBOX")
    
    def P2J4(self):
        print ("MODO_MANUAL_XBOX")

    def P2J5(self):
        print ("MODO_MANUAL_XBOX")  
    
    def P2J6(self):
        print ("MODO_MANUAL_XBOX") 
    
     
    def P3J1(self):
        print ("Modo manual_GUI")
    
    def P3J2(self):
        print ("MODO_MANUAL_XBOX")

    def P3J3(self):
        print ("MODO_MANUAL_XBOX")
    
    def P3J4(self):
        print ("MODO_MANUAL_XBOX")

    def P3J5(self):
        print ("MODO_MANUAL_XBOX")  
    
    def P3J6(self):
        print ("MODO_MANUAL_XBOX") 
    
    def save(self):
         self.f=open("Trayectoria1.py", "w")
         self.f.write ("M11 =" + str(self.M11)+ "\n")
         self.f.write ("M21 =" + str(self.M21)+ "\n")
         self.f.write ("M31 =" + str(self.M31)+ "\n")
         self.f.write ("M41 =" + str(self.M41)+ "\n")
         self.f.write ("M51 =" + str(self.M51)+ "\n")
         self.f.write ("M61 =" + str(self.M61)+ "\n")

         self.f.write ("M12 =" +str(self.M12)+ "\n")
         self.f.write ("M22 =" +str(self.M22)+ "\n")
         self.f.write ("M32 =" +str(self.M32)+ "\n")
         self.f.write ("M42 =" +str(self.M42)+ "\n")
         self.f.write ("M52 =" +str(self.M52)+ "\n")
         self.f.write ("M62 =" +str(self.M62)+ "\n")

         self.f.write ("M13 =" +str(self.M13)+ "\n")
         self.f.write ("M23 =" +str(self.M23)+ "\n")
         self.f.write ("M33 =" +str(self.M33)+ "\n")
         self.f.write ("M43 =" +str(self.M43)+ "\n")
         self.f.write ("M53 =" +str(self.M53)+ "\n")
         self.f.write ("M63 =" +str(self.M63)+ "\n")

         self.f.close()

    def printear(self):
        self.read()
        print(self.M11)
        print(self.M21)
        print(self.M31)
        print(self.M41)
        print(self.M51)
        print(self.M61)
        
        print(self.M12)
        print(self.M22)
        print(self.M32)
        print(self.M42)
        print(self.M52)
        print(self.M62)

        print(self.M13)
        print(self.M23)
        print(self.M33)
        print(self.M43)
        print(self.M53)
        print(self.M63)


    def plano(self):
        
        print('Entre a la funcion planear')
        # We can get the joint values from the group and adjust some of the values:
        self.joint_goal = self.move_group.get_current_joint_values()
        print(self.joint_goal)

        # joint_goal[1] = 0
        # joint_goal[2] = 0
        # joint_goal[3] = 0
        # joint_goal[4] = 0
        # joint_goal[5] = 0
        # joint_goal[6] = 0
       
        #cambiar joint values
        self.joint_goal[0] = float(self.M1)    #  // radians
        self.joint_goal[1] = float(self.M2)   #  // radians-0.6   1.37
        self.joint_goal[2] = float(self.M3)  #  // radians 0 2.5
        self.joint_goal[3] = float(self.M4) #  // radians -2.7 
        self.joint_goal[4] = float(self.M5)#  // radians 1.8
        self.joint_goal[5] = float(self.M6)#  // radians 2.3
        
       
        # The go command can be called with joint values, poses, or without any
        # parameters if you have already set the pose or joint target for the group
        self.move_group.set_joint_value_target(self.joint_goal)
        self.plan = self.move_group.go( wait=True)
        #plan = move_group.go(joint_goal, wait=True)
        print("after planning")
        # Calling ``stop()`` ensures that there is no residual movement
        self.move_group.stop()
        #joint_goal[0] =1.57  #;  // radians
        #joint_goal[1] = 0.0 #;  // radians
        #joint_goal[2] = 0.0 #;  // radians
        #joint_goal[3] = 0.0 #  // radians
        #joint_goal[4] = 0.0 #;  // radians
        #joint_goal[5] = 0.0 #;  // radians
        #move_group.execute(plan,  wait=True)
        #move_group.set_joint_value_target(joint_goal)
        # plan = move_group.go( wait=True)
        rospy.sleep(0.5)                                                 
        print("end")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    trayectoria1 = QtWidgets.QWidget()
    ui = Ui_trayectoria1()
    ui.setupUi(trayectoria1)
    trayectoria1.show()
    moveit_commander.roscpp_initialize(sys.argv)
    rospy.init_node('robot_plan', anonymous=True)
    rospy.loginfo("robot_plan")
    sys.exit(app.exec_())
